# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit paper-mapycusmaximus.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(mapycusmaximus)
library(geogrid)
library(sf)
library(units)
library(ggthemes)
library(cowplot)
library(RColorBrewer)
library(cartogram)
library(patchwork)


## ----data-cart, include=FALSE-------------------------------------------
# Library
# Load the population per states (source: https://www.census.gov/data/tables/2017/demo/popest/nation-total.html)
pop <- read.table("https://raw.githubusercontent.com/holtzy/R-graph-gallery/master/DATA/pop_US.csv", sep = ",", header = T)
pop$pop <- pop$pop / 1000000

# merge both
my_sf <- read_sf("https://andrew.carto.com/api/v2/sql?filename=us_states_hexgrid&q=select+*+from+andrew.us_states_hexgrid&format=geojson&bounds=&api_key=")
my_sf <- my_sf |>
  mutate(google_name = gsub(" \\(United States\\)", "", google_name))
my_sf <- my_sf |> left_join(pop, by = c("google_name" = "state"))

# Compute the cartogram, using this population information
# First we need to change the projection, we use Mercator (AKA Google Maps, EPSG 3857)
my_sf_merc <- st_transform(my_sf, 3857)
cartogram <- cartogram_cont(my_sf_merc, "pop")

# Back to original projection
cartogram <- st_transform(cartogram, st_crs(my_sf))


## ----plot-cart, echo=FALSE----------------------------------------------
ggplot(cartogram) +
  geom_sf(aes(fill = pop), linewidth = 0.05, alpha = 0.9, color = "black") +
  scale_fill_gradientn(
    colours = brewer.pal(7, "BuPu"), name = "population (in M)",
    labels = scales::label_comma(),
    guide = guide_legend(
      keyheight = unit(3, units = "mm"),
      keywidth = unit(12, units = "mm"),
      title.position = "top",
      label.position = "bottom"
    )
  ) +
  geom_sf_text(aes(label = iso3166_2), color = "white", size = 3, alpha = 0.8) +
  theme_void() +
  ggtitle("Another look on the US population") +
  theme(
    legend.position = c(0.5, 0.9),
    legend.direction = "horizontal",
    text = element_text(color = "#22211d"),
    plot.background = element_rect(fill = "#f5f5f9", color = NA),
    panel.background = element_rect(fill = "#f5f5f9", color = NA),
    legend.background = element_rect(fill = "#f5f5f9", color = NA),
    plot.title = element_text(size = 22, hjust = 0.5, color = "#4e4d47", margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")),
  )


## ----data-geo-grid, include=FALSE---------------------------------------

vic <- vic |> st_transform(3111)
vic <- vic |> 
 mutate(
  LGA_ABBR = case_when(
   LGA_NAME == "CARDINIA" ~ "CAR",
   LGA_NAME == "NILLUMBIK" ~ "NIL",
   LGA_NAME == "MITCHELL" ~ "MIT",
   LGA_NAME == "HUME" ~ "HUM",
   LGA_NAME == "MOIRA" ~ "MOI",
   LGA_NAME == "MURRINDINDI" ~ "MUR",
   LGA_NAME == "LODDON" ~ "LOD",
   LGA_NAME == "GLEN EIRA" ~ "GE",
   LGA_NAME == "GREATER SHEPPARTON" ~ "GS",
   LGA_NAME == "GANNAWARRA" ~ "GAN",
   LGA_NAME == "SURF COAST" ~ "SC",
   LGA_NAME == "WHITTLESEA" ~ "WHS",
   LGA_NAME == "MACEDON RANGES" ~ "MR",
   LGA_NAME == "GREATER DANDENONG" ~ "GD",
   LGA_NAME == "BAYSIDE" ~ "BAY",
   LGA_NAME == "MANSFIELD" ~ "MAN",
   LGA_NAME == "WEST WIMMERA" ~ "WW",
   LGA_NAME == "MILDURA" ~ "MIL",
   LGA_NAME == "HINDMARSH" ~ "HIN",
   LGA_NAME == "GOLDEN PLAINS" ~ "GP",
   LGA_NAME == "HORSHAM" ~ "HOR",
   LGA_NAME == "PYRENEES" ~ "PYR",
   LGA_NAME == "STRATHBOGIE" ~ "STR",
   LGA_NAME == "HOBSONS BAY" ~ "HB",
   LGA_NAME == "QUEENSCLIFFE" ~ "QUE",
   LGA_NAME == "SWAN HILL" ~ "SH",
   LGA_NAME == "MORNINGTON PENINSULA" ~ "MP",
   LGA_NAME == "SOUTH GIPPSLAND" ~ "SG",
   LGA_NAME == "SOUTHERN GRAMPIANS" ~ "SGR",
   LGA_NAME == "GLENELG" ~ "GLE",
   LGA_NAME == "CASEY" ~ "CAS",
   LGA_NAME == "KNOX" ~ "KNO",
   LGA_NAME == "NORTHERN GRAMPIANS" ~ "NG",
   LGA_NAME == "MONASH" ~ "MON",
   LGA_NAME == "BALLARAT" ~ "BAL",
   LGA_NAME == "MOONEE VALLEY" ~ "MV",
   LGA_NAME == "MERRI-BEK" ~ "MBK",
   LGA_NAME == "GREATER BENDIGO" ~ "GB",
   LGA_NAME == "CAMPASPE" ~ "CAM",
   LGA_NAME == "WARRNAMBOOL" ~ "WAR",
   LGA_NAME == "BASS COAST" ~ "BC",
   LGA_NAME == "ALPINE" ~ "ALP",
   LGA_NAME == "EAST GIPPSLAND" ~ "EG",
   LGA_NAME == "YARRIAMBIACK" ~ "YAK",
   LGA_NAME == "BULOKE" ~ "BUL",
   LGA_NAME == "TOWONG" ~ "TOW",
   LGA_NAME == "WODONGA" ~ "WOD",
   LGA_NAME == "INDIGO" ~ "IND",
   LGA_NAME == "HEPBURN" ~ "HEP",
   LGA_NAME == "WYNDHAM" ~ "WYN",
   LGA_NAME == "MOUNT ALEXANDER" ~ "MA",
   LGA_NAME == "CENTRAL GOLDFIELDS" ~ "CG",
   LGA_NAME == "WHITEHORSE" ~ "WH",
   LGA_NAME == "KINGSTON" ~ "KIN",
   LGA_NAME == "MARIBYRNONG" ~ "MAR",
   LGA_NAME == "ARARAT" ~ "ARA",
   LGA_NAME == "MOORABOOL" ~ "MOO",
   LGA_NAME == "WELLINGTON" ~ "WEL",
   LGA_NAME == "MAROONDAH" ~ "MARO",
   LGA_NAME == "DAREBIN" ~ "DAR",
   LGA_NAME == "MANNINGHAM" ~ "MANI",
   LGA_NAME == "BRIMBANK" ~ "BRI",
   LGA_NAME == "MELBOURNE" ~ "MEL",
   LGA_NAME == "BOROONDARA" ~ "BOR",
   LGA_NAME == "GREATER GEELONG" ~ "GEE",
   LGA_NAME == "STONNINGTON" ~ "STO",
   LGA_NAME == "BANYULE" ~ "BAN",
   LGA_NAME == "LATROBE" ~ "LAT",
   LGA_NAME == "YARRA" ~ "YAR",
   LGA_NAME == "WANGARATTA" ~ "WAN",
   LGA_NAME == "YARRA RANGES" ~ "YARAN",
   LGA_NAME == "PORT PHILLIP" ~ "PP",
   LGA_NAME == "MELTON" ~ "MELT",
   LGA_NAME == "COLAC OTWAY" ~ "CO",
   LGA_NAME == "CORANGAMITE" ~ "COR",
   LGA_NAME == "MOYNE" ~ "MOY",
   LGA_NAME == "FRANKSTON" ~ "FRA",
   LGA_NAME == "BENALLA" ~ "BEN",
   LGA_NAME == "BAW BAW" ~ "BB",
   # Alpine resorts / unincorporated islands
   grepl("ALPINE RESORT", LGA_NAME) ~ "AR",
   grepl("ISLAND", LGA_NAME) ~ "ISL",
   TRUE ~ NA_character_
  ),
  area_km2 = as.numeric(set_units(st_area(geometry), "km^2")))


original_shapes <- vic |> st_transform(27700)
new_cells_reg <- calculate_grid(shape = original_shapes, grid_type = "regular", seed = 3)
resultreg <- assign_polygons(original_shapes, new_cells_reg)


## ----geo-grid-plot, echo=FALSE------------------------------------------
ggplot(resultreg) +
 geom_sf(aes(fill = area_km2)) +
 geom_sf_label(aes(label = LGA_ABBR), size = 2) +
 scale_fill_viridis_c() +
 coord_sf() +
 theme_map()


## ----data-cow-plot, include=FALSE---------------------------------------
lga_inset <- vic[vic$LGA_NAME == "MELBOURNE", ]
main_map <- ggplot() +
 geom_sf(data = vic, fill = "lightgray", color = "white") +
 geom_sf(data = lga_inset, fill = "red", color = "red") + # Highlight the inset area
 theme_void() +
 labs(title = "Victoria")
inset_map <- ggplot() +
 geom_sf(data = lga_inset, fill = "lightblue", color = "darkblue") +
 theme_void() +
 labs(title = "Melbourne LGA")


## ----cow-plot-plot, echo=FALSE------------------------------------------
final_map <- ggdraw() +
 draw_plot(main_map, x = 0, y = 0, width = 1, height = 1) + # Main map occupies the whole canvas
 draw_plot(inset_map, x = 0.7, y = 0.7, width = 0.25, height = 0.25) # Inset map position and size

print(final_map)


## ----preparing-data, include=FALSE--------------------------------------

plot_fisheye_fgc <- function(original_coords, transformed_coords, 
  cx = 0, cy = 0, r_in = 0.34, r_out = 0.5) {

# Create data frames for plotting
  zones <- classify_zones(original_coords, cx, cy, r_in, r_out)

  original_df <- data.frame(
    x = original_coords[, 1],
    y = original_coords[, 2],
    zone = zones,
    type = "Original"
  )

  transformed_df <- data.frame(
    x = transformed_coords[, 1],
    y = transformed_coords[, 2], 
    zone = zones,
    type = "Transformed"
  )

  combined_df <- rbind(original_df, transformed_df)

  # Create the plot
  p <- ggplot(combined_df, aes(x = x, y = y, color = zone)) +
    geom_point(size = 1.5, alpha = 0.8) +
    scale_color_manual(values = c("focus" = "#c60000ff", 
      "glue" = "#a5a9e8ff", 
      "context" = "#FFCC00")) +
    facet_wrap(~type) +
    coord_fixed() +
    theme_minimal() +
    theme(
      panel.grid.minor = element_blank(),
      legend.title = element_blank()
    ) +
    labs(title = "Fisheye FGC Transformation",
    subtitle = paste("r_in =", r_in, ", r_out =", r_out))

  # Add zone boundary circles
  if (r_in > 0) {
    circle_in <- data.frame(
      x = cx + r_in * cos(seq(0, 2*pi, length.out = 100)),
      y = cy + r_in * sin(seq(0, 2*pi, length.out = 100))
    )
  p <- p + geom_path(data = circle_in, aes(x = x, y = y), 
    color = "red", linetype = "dashed", inherit.aes = FALSE)
  }

  circle_out <- data.frame(
    x = cx + r_out * cos(seq(0, 2*pi, length.out = 100)),
    y = cy + r_out * sin(seq(0, 2*pi, length.out = 100))
  )
  p <- p + geom_path(data = circle_out, aes(x = x, y = y), 
    color = "blue", linetype = "dashed", inherit.aes = FALSE)

    return(p)
}


## ----fgc-zones, echo=FALSE, fig.cap="The three zones of an FGC transformation. Points inside the focus (red) expand radially; points in the glue (blue) compress toward the focus boundary; context points (gold) remain fixed."----

grid <- create_test_grid()
grid_df <- as_tibble(grid)
transform <- fisheye_fgc(grid, cx = 0, cy = 0, r_in = 0.34, r_out = 0.5)
transform_df <- as_tibble(transform) |>
  dplyr::mutate(
    zone = attr(transform, "zones"),
    r_orig = attr(transform, "original_radius"),
    r_new  = attr(transform, "new_radius")
  )
arrows_df <- cbind(grid_df, transform_df)

ggplot() +
  # Draw arrows showing movement
  # Original points
  geom_point(
    data = grid_df, aes(x = x, y = y),
    size = 0.6, alpha = 0.7, color = "#8080e0ff"
  ) +
  # Transformed points
  geom_point(
    data = transform_df, aes(x = x_new, y = y_new, color = zone),
    size = 0.6, alpha = 0.7
  ) +
  scale_color_manual(values = c("focus" = "#c60000ff", 
  "glue" = "#070737ff", 
  "context" = "#FFCC00")) +
    geom_segment(
  data = arrows_df |>
    filter(
      zone != "context",
      sqrt((x_new - x)^2 + (y_new - y)^2) > 1e-6  # only draw if moved
    ),
  aes(x = x, y = y, xend = x_new, yend = y_new, color = zone),
  arrow = arrow(length = unit(0.02, "npc")),
  alpha = 0.6,
  size = 0.5
) +
  scale_color_manual(values = c("focus" = "#c60000ff", 
     "glue" = "#070737ff", 
     "context" = "#FFCC00")) +
  coord_equal() +
  theme_minimal(base_size = 14) +
  labs(title = "Fisheye Transformation: Point Movement", x = "x", y = "y")



## ----transformation-table, echo=FALSE-----------------------------------
# Table 1: Coordinate transformation across zones for selected points
samples <- transform_df |>
  group_by(zone) |>
  slice_head(n = 3) |> 
  ungroup()
idx <- as.numeric(rownames(samples))

orig_samples <- grid_df |>
  slice(idx)

samples <- samples |>
  cbind(orig_samples) |>
  select(x, y, x_new, y_new, zone, r_orig, r_new)

samples |>
  knitr::kable(
    caption = "Coordinate transformation across fisheye zones for selected points on a regular grid",
    digits = 3
  )


## ----preparing-hosp-data------------------------------------------------
hosp_point <- conn_fish |>
  st_drop_geometry() |>
  select(destination, long_hosp, lat_hosp) |>
  distinct() |>
  st_as_sf(coords = c("long_hosp", "lat_hosp"), crs = 4326) |>
  st_transform(crs = st_crs(vic))

racf_point <- conn_fish |>
  st_drop_geometry() |>
  select(source, long_racf, lat_racf) |>
  distinct() |>
  st_as_sf(coords = c("long_racf", "lat_racf"), crs = 4326) |>
  st_transform(crs = st_crs(vic))


## ----hospitals-basic-plot-----------------------------------------------
# Standard plot
plot_hosp <- ggplot(vic) + 
  geom_sf(fill = "grey90") +
  geom_sf(data = hosp_point, color = "red", size = 0.3, alpha = 1) +
  ggtitle("Standard: Melbourne hospitals") +
  theme_map()
plot_racf <- ggplot(vic) + 
  geom_sf(fill = "grey90") +
  geom_sf(data = racf_point, color = "blue", size = 0.3, alpha = 1) +
  ggtitle("Standard: Melbourne RACFs") +
  theme_map()

plot_hosp + plot_racf


## ----connection-plot----------------------------------------------------

ggplot(vic_fish) +
  geom_sf(fill = "grey90") +
  geom_sf(data = conn_fish, color = "black", size = 0.3, aes(alpha = weight)) +
  ggtitle("Melbourne hospitals and RACFs connection") +
  theme_map()


## ----fisheye-preparation------------------------------------------------
melbourne <- vic_fish |> filter(LGA_NAME == "MELBOURNE")
hosp_point2 <- hosp_point |>
  mutate(type = "hospital") |>
  rename(id = destination)

racf_point2 <- racf_point |>
  mutate(type = "racf") |>
  rename(id = source)

all_points <- bind_rows(hosp_point2, racf_point2)

all_points <- sf_fisheye(all_points, center = melbourne, zoom = 20, squeeze = 0.3, method = "expand")
scale_radii <- 1 - (((st_bbox(vic)["xmax"] - st_bbox(vic)["xmin"])  - (st_bbox(all_points)["xmax"] - st_bbox(all_points)["xmin"])) / (st_bbox(vic)["xmax"] - st_bbox(vic)["xmin"]))
vic_fisheye  <- sf_fisheye(vic, center = melbourne, r_in = 0.35 * scale_radii, r_out = 0.5 * scale_radii, zoom = 20, squeeze = 0.3, method = "expand")


## ----fisheye-plot-------------------------------------------------------
ggplot(vic_fisheye) +
  geom_sf(data = filter(vic_fisheye, LGA_NAME != "MELBOURNE"), fill = "grey", linewidth = 0.5) +
  geom_sf(data = filter(vic_fisheye, LGA_NAME == "MELBOURNE"), fill = "white", linewidth = 0.5) +
  geom_sf_label(data = melbourne, aes(label = LGA_NAME), size = 2, alpha = 0.2) +
  geom_sf(data = all_points, aes(color = type), size = 0.3, alpha = 0.5) +
  scale_color_manual(
  name = "Facility type",
  values = c("hospital" = "red", "racf" = "blue"),
  labels = c("Hospital", "RACF")) +
  ggtitle("Melbourne hospitals and RACFs connection") +
  theme_map()


## ----france-preparation-------------------------------------------------
map<-sf::read_sf('https://github.com/BjnNowak/lego_map/raw/main/data/france_sport.gpkg')

# Create classes
clean <- map |>
  mutate(clss=case_when(
    value<18~"1",
    value<20~"2",
    value<22~"3",
    value<24~"4",
    value<26~"5",
    TRUE~"6"
  ))

# Set color palette
pal <- c("#bb3e03","#ee9b00","#e9d8a6","#94d2bd","#0a9396","#005f73")
# Set color background
bck <- "#001219"

# Set theme 
theme_custom <- theme_void()+
  theme(
    plot.title = element_text(size = 14, face = "bold", hjust = 0.5, color = "#ffffffff"),
    plot.margin = margin(1,1,10,1,"pt"),
    plot.background = element_rect(fill=bck,color=NA),
    legend.position = "bottom",
    legend.title = element_text(hjust=0.5,color="white",face="bold"),
    legend.text = element_text(color="white")
  )

# Make grid
grd <- st_make_grid(
    clean, # map name 
    n = c(60,60) # number of cells per longitude/latitude
  )|>
  # convert back to sf object
  st_sf()|>
  # add a unique id to each cell 
  # (will be useful later to get back centroids data)
  mutate(id=row_number())
  
# Extract centroids
cent<-grd|>
  st_centroid()

# Intersect centroids with basemap
cent_clean<-cent|>
  st_intersection(clean)

# Make a centroid without geom
# (convert from sf object to tibble)
cent_no_geom <- cent_clean|>
  st_drop_geometry()

# Join with grid thanks to id column
grd_clean<-grd|>
  #filter(id%in%sel)|>
  left_join(cent_no_geom)

grd_clean <- grd_clean |> rename("geometry" = "st_make_grid.clean..n...c.60..60..")
cent_clean <- cent_clean |> rename("geometry" = "st_make_grid.clean..n...c.60..60..")

grd_clean_fish <- sf_fisheye(grd_clean)
cent_clean_fish <- sf_fisheye(cent_clean)



## ----france-plots-------------------------------------------------------
plot_frc_1 <- ggplot() +
  geom_sf(
    grd_clean |> drop_na(),
    mapping = aes(geometry = geometry, fill = clss)
  ) +
  geom_sf(
    cent_clean,
    mapping = aes(geometry = geometry),
    fill = NA, pch = 21, size = 0.5
  ) +
  labs(title = "Before fisheye",
    fill="Percentage of population \nis a member of a sport association") +
  scale_fill_manual(
    values = pal,
    label = c("< 18 %","< 20 %","< 22 %","< 24 %","< 26 %", "≥ 26 %")
  ) +
  guides(
    fill = guide_legend(
      nrow = 1,
      title.position = "top",
      label.position = "bottom"
    )
  ) +
  theme_custom


plot_frc_2 <- ggplot() +
  geom_sf(
    grd_clean_fish |> drop_na(),
    mapping = aes(geometry = geometry, fill = clss)
  ) +
  geom_sf(
    cent_clean_fish,
    mapping = aes(geometry = geometry),
    fill = NA, pch = 21, size = 0.5
  ) +
  guides(
    fill = guide_legend(
      nrow = 1,
      title.position = "top",
      label.position = "bottom"
    )
  ) +
  labs(title = "After fisheye",
    fill="Percentage of population \nis a member of a sport association") +

  scale_fill_manual(
    values = pal,
    label = c("< 18 %","< 20 %","< 22 %","< 24 %","< 26 %", "≥ 26 %")
  ) +
  theme_custom


## ----france-comparison--------------------------------------------------
plot_frc_1 + plot_frc_2

